/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificateCheckRouteImport } from './routes/certificate-check'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EducationAidesRouteImport } from './routes/education-aides'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAdmissionsRouteImport } from './routes/_authenticated/admin/admissions'
import { Route as AuthenticatedAdminCertificateCheckRouteImport } from './routes/_authenticated/admin/certificate-check'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminEducationAidesRouteImport } from './routes/_authenticated/admin/education-aides'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminFacultyRouteImport } from './routes/_authenticated/admin/faculty'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin/faqs'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminHomePageRouteImport } from './routes/_authenticated/admin/home-page'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin/notices'
import { Route as AuthenticatedAdminRoutinesRouteImport } from './routes/_authenticated/admin/routines'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated/admin/traffic'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoursesCategorySlugRouteImport } from './routes/courses.category.$slug'
import { Route as AuthenticatedAdminCoursesNewRouteImport } from './routes/_authenticated/admin/courses.new'
import { Route as AuthenticatedAdminFacultyNewRouteImport } from './routes/_authenticated/admin/faculty.new'
import { Route as AuthenticatedAdminCoursesIdEditRouteImport } from './routes/_authenticated/admin/courses.$id.edit'
import { Route as AuthenticatedAdminFacultyIdEditRouteImport } from './routes/_authenticated/admin/faculty.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCheckRoute = CertificateCheckRouteImport.update({
  id: '/certificate-check',
  path: '/certificate-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationAidesRoute = EducationAidesRouteImport.update({
  id: '/education-aides',
  path: '/education-aides',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAdmissionsRoute =
  AuthenticatedAdminAdmissionsRouteImport.update({
    id: '/admissions',
    path: '/admissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCertificateCheckRoute =
  AuthenticatedAdminCertificateCheckRouteImport.update({
    id: '/certificate-check',
    path: '/certificate-check',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEducationAidesRoute =
  AuthenticatedAdminEducationAidesRouteImport.update({
    id: '/education-aides',
    path: '/education-aides',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFacultyRoute =
  AuthenticatedAdminFacultyRouteImport.update({
    id: '/faculty',
    path: '/faculty',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomePageRoute =
  AuthenticatedAdminHomePageRouteImport.update({
    id: '/home-page',
    path: '/home-page',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoutinesRoute =
  AuthenticatedAdminRoutinesRouteImport.update({
    id: '/routines',
    path: '/routines',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCategorySlugRoute = CoursesCategorySlugRouteImport.update({
  id: '/courses/category/$slug',
  path: '/courses/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCoursesNewRoute =
  AuthenticatedAdminCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminFacultyNewRoute =
  AuthenticatedAdminFacultyNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminFacultyRoute,
  } as any)
const AuthenticatedAdminCoursesIdEditRoute =
  AuthenticatedAdminCoursesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminFacultyIdEditRoute =
  AuthenticatedAdminFacultyIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedAdminFacultyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/certificate-check': typeof CertificateCheckRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/education-aides': typeof EducationAidesRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/certificate-check': typeof AuthenticatedAdminCertificateCheckRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/education-aides': typeof AuthenticatedAdminEducationAidesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRouteWithChildren
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/home-page': typeof AuthenticatedAdminHomePageRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/routines': typeof AuthenticatedAdminRoutinesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/category/$slug': typeof CoursesCategorySlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/faculty/new': typeof AuthenticatedAdminFacultyNewRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/admin/faculty/$id/edit': typeof AuthenticatedAdminFacultyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/certificate-check': typeof CertificateCheckRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/education-aides': typeof EducationAidesRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/certificate-check': typeof AuthenticatedAdminCertificateCheckRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/education-aides': typeof AuthenticatedAdminEducationAidesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faculty': typeof AuthenticatedAdminFacultyRouteWithChildren
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/home-page': typeof AuthenticatedAdminHomePageRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/routines': typeof AuthenticatedAdminRoutinesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/category/$slug': typeof CoursesCategorySlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/faculty/new': typeof AuthenticatedAdminFacultyNewRoute
  '/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/admin/faculty/$id/edit': typeof AuthenticatedAdminFacultyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/certificate-check': typeof CertificateCheckRoute
  '/certification': typeof CertificationRoute
  '/contact': typeof ContactRoute
  '/education-aides': typeof EducationAidesRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/testimonials': typeof TestimonialsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/_authenticated/admin/certificate-check': typeof AuthenticatedAdminCertificateCheckRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/education-aides': typeof AuthenticatedAdminEducationAidesRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/faculty': typeof AuthenticatedAdminFacultyRouteWithChildren
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/home-page': typeof AuthenticatedAdminHomePageRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/routines': typeof AuthenticatedAdminRoutinesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/category/$slug': typeof CoursesCategorySlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/_authenticated/admin/faculty/new': typeof AuthenticatedAdminFacultyNewRoute
  '/_authenticated/admin/courses/$id/edit': typeof AuthenticatedAdminCoursesIdEditRoute
  '/_authenticated/admin/faculty/$id/edit': typeof AuthenticatedAdminFacultyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/certificate-check'
    | '/certification'
    | '/contact'
    | '/education-aides'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/notices'
    | '/testimonials'
    | '/admin'
    | '/admin/login'
    | '/courses/$slug'
    | '/courses/'
    | '/admin/admissions'
    | '/admin/certificate-check'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/education-aides'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/home-page'
    | '/admin/notices'
    | '/admin/routines'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/traffic'
    | '/admin/users'
    | '/api/auth/$'
    | '/courses/category/$slug'
    | '/admin/'
    | '/admin/courses/new'
    | '/admin/faculty/new'
    | '/admin/courses/$id/edit'
    | '/admin/faculty/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/certificate-check'
    | '/certification'
    | '/contact'
    | '/education-aides'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/notices'
    | '/testimonials'
    | '/admin/login'
    | '/courses/$slug'
    | '/courses'
    | '/admin/admissions'
    | '/admin/certificate-check'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/education-aides'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/faqs'
    | '/admin/gallery'
    | '/admin/home-page'
    | '/admin/notices'
    | '/admin/routines'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/traffic'
    | '/admin/users'
    | '/api/auth/$'
    | '/courses/category/$slug'
    | '/admin'
    | '/admin/courses/new'
    | '/admin/faculty/new'
    | '/admin/courses/$id/edit'
    | '/admin/faculty/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admission'
    | '/auth'
    | '/certificate-check'
    | '/certification'
    | '/contact'
    | '/education-aides'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/notices'
    | '/testimonials'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/courses/$slug'
    | '/courses/'
    | '/_authenticated/admin/admissions'
    | '/_authenticated/admin/certificate-check'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/education-aides'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/faculty'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/home-page'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/routines'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/traffic'
    | '/_authenticated/admin/users'
    | '/api/auth/$'
    | '/courses/category/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/courses/new'
    | '/_authenticated/admin/faculty/new'
    | '/_authenticated/admin/courses/$id/edit'
    | '/_authenticated/admin/faculty/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  CertificateCheckRoute: typeof CertificateCheckRoute
  CertificationRoute: typeof CertificationRoute
  ContactRoute: typeof ContactRoute
  EducationAidesRoute: typeof EducationAidesRoute
  FacultyRoute: typeof FacultyRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NoticesRoute: typeof NoticesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoursesCategorySlugRoute: typeof CoursesCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate-check': {
      id: '/certificate-check'
      path: '/certificate-check'
      fullPath: '/certificate-check'
      preLoaderRoute: typeof CertificateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-aides': {
      id: '/education-aides'
      path: '/education-aides'
      fullPath: '/education-aides'
      preLoaderRoute: typeof EducationAidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/admissions': {
      id: '/_authenticated/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AuthenticatedAdminAdmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/certificate-check': {
      id: '/_authenticated/admin/certificate-check'
      path: '/certificate-check'
      fullPath: '/admin/certificate-check'
      preLoaderRoute: typeof AuthenticatedAdminCertificateCheckRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/education-aides': {
      id: '/_authenticated/admin/education-aides'
      path: '/education-aides'
      fullPath: '/admin/education-aides'
      preLoaderRoute: typeof AuthenticatedAdminEducationAidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faculty': {
      id: '/_authenticated/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AuthenticatedAdminFacultyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/home-page': {
      id: '/_authenticated/admin/home-page'
      path: '/home-page'
      fullPath: '/admin/home-page'
      preLoaderRoute: typeof AuthenticatedAdminHomePageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/routines': {
      id: '/_authenticated/admin/routines'
      path: '/routines'
      fullPath: '/admin/routines'
      preLoaderRoute: typeof AuthenticatedAdminRoutinesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/category/$slug': {
      id: '/courses/category/$slug'
      path: '/courses/category/$slug'
      fullPath: '/courses/category/$slug'
      preLoaderRoute: typeof CoursesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/courses/new': {
      id: '/_authenticated/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/faculty/new': {
      id: '/_authenticated/admin/faculty/new'
      path: '/new'
      fullPath: '/admin/faculty/new'
      preLoaderRoute: typeof AuthenticatedAdminFacultyNewRouteImport
      parentRoute: typeof AuthenticatedAdminFacultyRoute
    }
    '/_authenticated/admin/courses/$id/edit': {
      id: '/_authenticated/admin/courses/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/courses/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/faculty/$id/edit': {
      id: '/_authenticated/admin/faculty/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/faculty/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminFacultyIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminFacultyRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesNewRoute: typeof AuthenticatedAdminCoursesNewRoute
  AuthenticatedAdminCoursesIdEditRoute: typeof AuthenticatedAdminCoursesIdEditRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesNewRoute: AuthenticatedAdminCoursesNewRoute,
    AuthenticatedAdminCoursesIdEditRoute: AuthenticatedAdminCoursesIdEditRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminFacultyRouteChildren {
  AuthenticatedAdminFacultyNewRoute: typeof AuthenticatedAdminFacultyNewRoute
  AuthenticatedAdminFacultyIdEditRoute: typeof AuthenticatedAdminFacultyIdEditRoute
}

const AuthenticatedAdminFacultyRouteChildren: AuthenticatedAdminFacultyRouteChildren =
  {
    AuthenticatedAdminFacultyNewRoute: AuthenticatedAdminFacultyNewRoute,
    AuthenticatedAdminFacultyIdEditRoute: AuthenticatedAdminFacultyIdEditRoute,
  }

const AuthenticatedAdminFacultyRouteWithChildren =
  AuthenticatedAdminFacultyRoute._addFileChildren(
    AuthenticatedAdminFacultyRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdmissionsRoute: typeof AuthenticatedAdminAdmissionsRoute
  AuthenticatedAdminCertificateCheckRoute: typeof AuthenticatedAdminCertificateCheckRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEducationAidesRoute: typeof AuthenticatedAdminEducationAidesRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFacultyRoute: typeof AuthenticatedAdminFacultyRouteWithChildren
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHomePageRoute: typeof AuthenticatedAdminHomePageRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminRoutinesRoute: typeof AuthenticatedAdminRoutinesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdmissionsRoute: AuthenticatedAdminAdmissionsRoute,
    AuthenticatedAdminCertificateCheckRoute:
      AuthenticatedAdminCertificateCheckRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEducationAidesRoute:
      AuthenticatedAdminEducationAidesRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminFacultyRoute: AuthenticatedAdminFacultyRouteWithChildren,
    AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminHomePageRoute: AuthenticatedAdminHomePageRoute,
    AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
    AuthenticatedAdminRoutinesRoute: AuthenticatedAdminRoutinesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  CertificateCheckRoute: CertificateCheckRoute,
  CertificationRoute: CertificationRoute,
  ContactRoute: ContactRoute,
  EducationAidesRoute: EducationAidesRoute,
  FacultyRoute: FacultyRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NoticesRoute: NoticesRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminLoginRoute: AdminLoginRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoursesCategorySlugRoute: CoursesCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
